copy::
	cp ../run1/etot.tr set2/etot_AVS.tr
	cp ../run2/etot.tr set2/etot_Lang.tr
	cp ../run3/etot.tr set2/etot_NHCP100.tr
	cp ../run4/etot.tr set2/etot_VRSDt100.tr
	cp ../run5/etot.tr set2/etot_VRSDt30.tr
